# Generated by Django 5.1.4 on 2025-01-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConsulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateTimeField(help_text='Fecha y hora de la consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(help_text='Médico relacionado con la consulta', on_delete=django.db.models.deletion.CASCADE, to='AppConsulta.medico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.TextField(help_text='Motivo de la consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente relacionado con la consulta', on_delete=django.db.models.deletion.CASCADE, to='AppConsulta.paciente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellido',
            field=models.CharField(help_text='Apellido del médico', max_length=30),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(help_text='Correo electrónico del médico', max_length=254),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(help_text='Especialidad del médico', max_length=30),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(help_text='Nombre del médico', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(help_text='Apellido del paciente', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(help_text='Correo electrónico del paciente', max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Fecha de nacimiento (AAAA-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(help_text='Nombre del paciente', max_length=30),
        ),
    ]
