# Generated by Django 5.1.4 on 2025-01-27 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConsulta', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la consulta'),
        ),
    ]
